services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: medarchive
      POSTGRES_USER: medarchive
      POSTGRES_PASSWORD: medarchive
    ports:
      - "5432:5432"
    volumes:
      - medarchive_postgres:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  medarchive_postgres:
